---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  type: NodePort
  selector:
    component: kibana
  ports:
  - port: 5601
    targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        #image: docker.elastic.co/kibana/kibana:6.5.4
        image: docker.elastic.co/kibana/kibana:7.16.2
        env:
        - name:  LANG
          value: ja_JP.UTF-8
        - name: TZ
          value: Asia/Tokyo
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: I18N_LOCALE
          value: "ja-JP"
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: elasticsearch_username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kibana-config
              key: elasticsearch_password
        envFrom:
        - configMapRef:
            name: kibana-config
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        volumeMounts:
        - name: kibana-my-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: kibana-my-config
        configMap:
          name: kibana-my-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    component: kibana
data:
  elasticsearch_username: elastic
  elasticsearch_password: v24qc15WWtxbIgt4boR2 # it needs to be changed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-my-config
  labels:
    component: kibana
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    i18n.locale: “ja-JP”
    xpack.security.authc.providers:
      anonymous.anonymous1:
        order: 0
        #credentials: "elasticsearch_anonymous_user"
        credentials:
          username: "elastic"
          password: "v24qc15WWtxbIgt4boR2"
---
